const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');const root=require('path').resolve(__dirname,'..');const h=fs.readFileSync(process.env.FOURMANS_HTML||root+'/index.html','utf8'),data=JSON.parse(fs.readFileSync(root+'/4mans_app_data.json','utf8'));const decode=s=>s.replace(/&quot;/g,'"').replace(/&#039;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');
class Element{constructor(tag='div',attrs={},parent=null){this.tagName=tag;this.attrs=attrs;this.parentElement=parent;this.children=[];this._html='';this.style={};this.scrollTop=0;this.value=attrs.value||'';this.hidden='hidden'in attrs;this.disabled='disabled'in attrs;this.id=attrs.id||'';this.dataset={};for(const [k,v]of Object.entries(attrs))if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=v;const set=new Set((attrs.class||'').split(/\s+/).filter(Boolean));this.classList={add:(...c)=>c.forEach(x=>set.add(x)),remove:(...c)=>c.forEach(x=>set.delete(x)),contains:c=>set.has(c),toggle:(c,v)=>{const yes=v??!set.has(c);yes?set.add(c):set.delete(c);return yes}};}set innerHTML(value){this._html=value;this.children=parse(value,this);if(this.tagName==='select'){const opts=this.children.filter(x=>x.tagName==='option');this.value=(opts.find(x=>'selected'in x.attrs)||opts[0])?.value||'';}}get innerHTML(){return this._html}setAttribute(k,v){this.attrs[k]=v}matches(selector){let s=selector.trim();const attrs=[...s.matchAll(/\[([^=\]]+)(?:="([^"]*)")?\]/g)];for(const [,k,v]of attrs)if(!(k in this.attrs)||v!==undefined&&this.attrs[k]!==v)return false;s=s.replace(/\[[^\]]+\]/g,'');const id=s.match(/#([\w-]+)/)?.[1];if(id&&this.id!==id)return false;for(const [,c]of s.matchAll(/\.([\w-]+)/g))if(!this.classList.contains(c))return false;const tag=s.match(/^[\w-]+/)?.[0];return !tag||this.tagName===tag;}querySelectorAll(selector){const parts=selector.trim().split(/\s+(?![^\[]*\])/);const all=[];function visit(el){for(const child of el.children){if(child.matches(parts.at(-1))){let parent=child.parentElement,ok=true;for(let i=parts.length-2;i>=0;i--){while(parent&&!parent.matches(parts[i]))parent=parent.parentElement;if(!parent){ok=false;break}parent=parent.parentElement;}if(ok)all.push(child);}visit(child)}}visit(this);return all;}querySelector(s){return this.querySelectorAll(s)[0]||null}closest(s){let e=this;while(e&&!e.matches(s))e=e.parentElement;return e;}showModal(){this.open=true}close(){this.open=false}addEventListener(){}remove(){const i=this.parentElement.children.indexOf(this);this.parentElement.children.splice(i,1)}}
function parse(html,parent){const container={children:[]},stack=[container];let match;const re=/<\/?([a-zA-Z][\w-]*)([^>]*)>|([^<]+)/g;while(match=re.exec(html)){if(match[3]){const e=stack.at(-1);e.textContent=(e.textContent||'')+decode(match[3]);if(e.tagName==='option'&&!('value'in e.attrs))e.value=(e.textContent||'').trim();continue;}if(match[0].startsWith('</')){if(stack.length>1)stack.pop();continue;}const attrs={};for(const a of match[2].matchAll(/([\w:-]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s]+)))?/g))attrs[a[1]]=decode(a[2]??a[3]??a[4]??'');const node=new Element(match[1].toLowerCase(),attrs,stack.at(-1)===container?parent:stack.at(-1));stack.at(-1).children.push(node);if(!['input','img','br','meta','link','hr'].includes(node.tagName))stack.push(node);}return container.children;}
const doc=new Element('document');doc.innerHTML=h.replace(/<style>[\s\S]*?<\/style>/,'').replace(/<script>[\s\S]*?<\/script>/,'');doc.body=doc.querySelector('body');doc.documentElement=doc.querySelector('html');doc.hidden=false;const $=s=>doc.querySelector(s),ctx=vm.createContext({console,Intl,Date,data,document:doc,window:{scrollTo(){}},localStorage:{getItem(){return null},setItem(){}},location:{hash:''},navigator:{},setInterval(){},AbortSignal,FormData,fetch:async()=>{throw Error('Offline')}});vm.runInContext(h.match(/<script>([\s\S]*?)<\/script>/)[1].replace(/boot\(\);\s*$/,''),ctx);const run=s=>vm.runInContext(s,ctx);run("DATA=data;SESSION_USER={id:'commissioner',member:'nactasty',role:'commissioner'};NFL_STATE={season:'2026',week:3,phase:'regular'};initSelectors();populateTeamFilters();updatePositionFilter('stats');updatePositionFilter('own');");
for(const year of ['2025','2026']){run(`YEAR='${year}';renderStandings();LEAGUE_VIEW='season';renderLeagues();renderAnalysis();`);assert.equal(doc.querySelectorAll('.league-card').length,data.seasons[year].leagues.length);assert.ok(!$('#stand-cards').innerHTML.includes('NaN'));}
run("YEAR='2026';show('leagues-screen');");assert.equal(run('LEAGUE_VIEW'),'week');assert.equal(doc.querySelectorAll('.league-card .expand').length,0);assert.equal(doc.querySelectorAll('[data-week-open]').length,23);assert.ok($('#league-week-label').textContent.includes('Week 3'));
const first=data.seasons['2026'].leagues[0],wk=first.weeks.find(w=>w.week===3),expected=wk.rosters.find(r=>r.manager==='nactasty').pf;assert.ok($('#league-list').innerHTML.includes('data-pf="'+expected+'"'));
const savedUpcoming=data.seasons['2026'].leagues.map(l=>l.weeks.filter(w=>w.week===4));data.seasons['2026'].leagues.forEach(l=>l.weeks=l.weeks.filter(w=>w.week!==4));
run("NFL_STATE.week=4;renderLeagues();");assert.ok($('#league-week-label').textContent.includes('Week 4'));assert.equal(doc.querySelectorAll('.league-card .expand').length,0);assert.ok($('#league-list').innerHTML.includes('Current-week snapshot not saved yet'));assert.ok(doc.querySelectorAll('[data-week-open]').every(b=>b.disabled));
const pending={week:4,awaiting_scores:true,rows:[],rosters:wk.rosters.map(r=>({...r,pf:0,players_points:Object.fromEntries(Object.keys(r.players_points).map(k=>[k,0]))}))};data.seasons['2026'].leagues[0].weeks.push(pending);run('renderLeagues()');const pendingCard=doc.querySelectorAll('.league-card').find(c=>c.dataset.league===first.league_id);assert.equal(pendingCard.querySelectorAll('.pred-avatar').length,4);assert.equal(pendingCard.querySelector('[data-week-open]').disabled,false);pendingCard.querySelector('[data-week-open]').onclick();assert.ok($('#week-detail-content').innerHTML.includes('Awaiting scores'));assert.ok(!$('#week-detail-content').innerHTML.includes('1ST'));run('closeWeekDetail()');data.seasons['2026'].leagues[0].weeks.pop();data.seasons['2026'].leagues.forEach((l,i)=>l.weeks.push(...savedUpcoming[i]));
run("NFL_STATE.week=3;setLeagueMode('season');");assert.equal(doc.querySelectorAll('.league-card .expand').length,23);for(const mode of ['season','week'])for(const manager of data.managers.map(m=>m.key))for(const sort of ['most','fewest']){run(`LEAGUE_VIEW='${mode}';$('#league-manager').value='${manager}';LEAGUE_SORT='${sort}';renderLeagues();`);const scores=doc.querySelectorAll('.league-card').map(e=>run(`leagueRows(DATA.seasons[YEAR].leagues.find(l=>l.league_id==='${e.dataset.league}')).find(r=>r.manager==='${manager}').pf`));assert.ok(scores.every((v,i)=>!i||(sort==='most'?v<=scores[i-1]:v>=scores[i-1])));}
assert.ok($('#league-view-week').closest('.sticky-manager'));assert.equal($('#league-sort').children.length,3);
run(`openLeagueDetail('${first.league_id}','nactasty');`);assert.equal(doc.querySelectorAll('#league-detail-content .league-standing').length,4);assert.ok($('#league-detail-content').innerHTML.includes('behind first'));const selected=doc.querySelectorAll('[data-league-manager]')[1];selected.onclick();assert.equal(run('LEAGUE_DETAIL.manager'),selected.dataset.leagueManager);doc.querySelectorAll('[data-league-detail-week]')[0].onclick();assert.ok($('#week-detail-screen').classList.contains('active'));assert.equal(run('WEEK_DETAIL.manager'),selected.dataset.leagueManager);run('closeWeekDetail()');assert.ok($('#league-detail-screen').classList.contains('active'));
run("show('login-screen');");assert.equal(doc.querySelectorAll('.detail-screen.active').length,0);
run("YEAR='2026';$('#stats-side').value='All';$('#stats-manager').value='nactasty';$('#stats-position').value='WR';renderStats();");assert.ok($('#stats-table thead').innerHTML.includes('TARGETS'));assert.ok($('#stats-table thead').innerHTML.includes('OWNED %'));assert.ok(!$('#stats-table thead').innerHTML.includes('PASS YDS'));assert.ok(doc.querySelectorAll('#stats-table [data-analysis-player]').length>0);const pid=data.seasons['2026'].stats.find(r=>r.ownership.nactasty>0)?.player_id;run(`openAnalysisPlayerDetail('${pid}');`);assert.ok($('#player-detail-content').innerHTML.includes('Weekly production'));assert.ok($('#player-detail-content').innerHTML.includes('Ownership by manager'));run('closePlayerDetail()');assert.ok(!$('#player-detail-screen').classList.contains('active'));
for(const p of ['QB','RB','TE','K','LB']){run(`$('#stats-position').value='${p}';renderStats();`);assert.ok(!$('#stats-table tbody').innerHTML.includes('NaN'));}
run("toggleAnalysisFull('stats',true)");assert.ok($('#stats-table').closest('.table-shell').classList.contains('table-fullscreen'));run("show('login-screen')");assert.ok(!$('#stats-table').closest('.table-shell').classList.contains('table-fullscreen'));
run("const tieRows=[{manager:'nactasty',pf:100},{manager:'jpagonis',pf:100},{manager:'TheChavenator',pf:90},{manager:'bingbongtinydong',pf:80}];");const payouts=run('leaguePayouts(tieRows)');assert.equal(payouts.nactasty,5);assert.equal(payouts.jpagonis,5);assert.equal(Object.values(payouts).reduce((a,b)=>a+b,0),0);assert.equal(run('rankedRows(tieRows)[2].place'),3);for(let leaders=1;leaders<=4;leaders++){ctx.leaders=leaders;const p=run("leaguePayouts(data.managers.map((m,i)=>({manager:m.key,pf:i<leaders?100:50})))");assert.ok(Math.abs(Object.values(p).reduce((a,b)=>a+b,0))<.000001);}
run("PRED={user:SESSION_USER,leaderboard:[],predictions:[{id:'one',author:'jpagonis',title:'Test',criteria:'Test',amount:1000,mode:'each',version:0,deadline:Date.now()+86400000,outcome:null}],responses:[],rulings:[],members:data.managers.map(m=>m.key),balances:{nactasty:{jpagonis:1000},jpagonis:{nactasty:-1000,bingbongtinydong:-2000},bingbongtinydong:{jpagonis:2000}},seasonStatus:null};PRED_YEAR='2026';PRED_FILTER='response';renderPredictions();");assert.ok($('#pred-filter-response').textContent.includes('(1)'));assert.ok($('#pred-balances').innerHTML.includes('Owes nactasty <strong>$10.00'));assert.ok($('#pred-balances').innerHTML.includes('Owes bingbongtinydong <strong>$20.00'));assert.ok($('#pred-balances').innerHTML.includes('Total owed $30.00'));assert.equal(doc.querySelectorAll('#pred-balances .manager-debts').length,4);assert.equal($('#pred-close-season').hidden,true);assert.ok($('#pred-open').innerHTML.includes('Accept $10.00'));
run("PRED.responses=[{prediction_id:'one',member:'nactasty',decision:'decline',amount:0}];renderPredictions();");assert.ok($('#pred-open').innerHTML.includes('You’re caught up'));
run("PRED.predictions[0].outcome='didnt';PRED.predictions[0].author='jpagonis';PRED.responses=[{prediction_id:'one',member:'bingbongtinydong',decision:'accept',amount:2000}];PRED_FILTER='all';renderPredictions();");assert.equal($('#pred-close-season').hidden,false);assert.equal($('#pred-close-season').textContent,'Close Season');assert.ok($('#pred-history').innerHTML.includes('<h4>Results</h4>'));assert.ok($('#pred-history').innerHTML.includes('jpagonis owes bingbongtinydong <strong>$20.00'));assert.ok(!$('#pred-history details .pred-responses').innerHTML.includes('pred-net'));
for(const kind of ['stats','own']){run(`setAnalysisSide('${kind}','Defense')`);assert.ok($('#'+kind+'-position').children.slice(1).every(x=>run(`positionSide('${x.value}')`)==='defense'));run(`setAnalysisSide('${kind}','Offense')`);assert.ok($('#'+kind+'-position').children.slice(1).every(x=>run(`positionSide('${x.value}')`)==='offense'));}
assert.ok(!$('#stats-table thead').innerHTML.includes('AVG LEAGUE FPTS'));assert.equal(doc.querySelectorAll('.analysis-more').length,0);assert.ok(!$('#analysis-fpts-help'));

// Exercise the wired manager-change event, preserving the chosen point sort.
run("YEAR='2026';NFL_STATE.week=3;LEAGUE_VIEW='season';wireLeagueControls();");
for(const mode of ['season','week'])for(const sort of ['most','fewest','place']){
 run(`LEAGUE_VIEW='${mode}';$('#league-sort').value='${sort}';$('#league-sort').onchange();`);
 for(const manager of data.managers.map(m=>m.key)){
  run(`$('#league-manager').value='${manager}';$('#league-manager').onchange();`);
  const leagues=doc.querySelectorAll('.league-card').map(c=>data.seasons['2026'].leagues.find(l=>l.league_id===c.dataset.league));
  const values=leagues.map(l=>{ctx.l=l;return run(`leagueSortValue(l,'${manager}')`)});
  assert.ok(values.every((v,i)=>!i||!v||!values[i-1]||(sort==='place'?(v.place>values[i-1].place||v.place===values[i-1].place&&v.gap>=values[i-1].gap):sort==='most'?v.points<=values[i-1].points:v.points>=values[i-1].points)));
  assert.ok($('#league-list').innerHTML.includes(run(`esc(managerLabel('${manager}'))`)));
 }
}
// Independent place-sort fixture: bigger first-place lead, smaller runner-up gap.
ctx.fixture=[{name:'second far',totals:[{manager:'nactasty',pf:80},{manager:'jpagonis',pf:100}]},{name:'first small',totals:[{manager:'nactasty',pf:101},{manager:'jpagonis',pf:100}]},{name:'second close',totals:[{manager:'nactasty',pf:99},{manager:'jpagonis',pf:100}]},{name:'first big',totals:[{manager:'nactasty',pf:150},{manager:'jpagonis',pf:100}]}];
assert.deepEqual(Array.from(run("LEAGUE_VIEW='season';LEAGUE_SORT='place';fixture.sort((a,b)=>compareManagerLeagues(a,b,'nactasty')).map(l=>l.name)")),['first big','first small','second close','second far']);
run("show('leagues-screen');setLeagueMode('season');");const card=doc.querySelectorAll('.league-card')[0],league=data.seasons['2026'].leagues.find(l=>l.league_id===card.dataset.league);card.querySelector('.expand').onclick();assert.ok($('#league-history-screen').classList.contains('active'));assert.equal(doc.querySelectorAll('[data-history-week]').length,league.weeks.length);assert.equal(card.querySelectorAll('.weeks').length,0);$('#league-history-screen').scrollTop=420;doc.querySelectorAll('[data-history-week]')[0].onclick();assert.ok($('#week-detail-screen').classList.contains('active'));run('closeWeekDetail()');assert.equal($('#league-history-screen').scrollTop,420);const order=doc.querySelectorAll('.league-card').map(c=>c.dataset.league);$('#league-history-back').onclick();assert.deepEqual(doc.querySelectorAll('.league-card').map(c=>c.dataset.league),order);
// Schema completeness and actual QB profile content in both season and week views.
for(const side of ['offense','defense']){ctx.side=side;const cols=run("analysisColumns('All',side,'All').map(c=>c[0])");for(const pos of side==='offense'?['QB','RB','WR','TE','K']:['DEF','IDP']){ctx.pos=pos;for(const key of run('positionStatSchema(pos).flatMap(s=>s.items.map(i=>i[0]))'))assert.ok(cols.includes(key));}}
const qb=data.seasons['2026'].stats.find(r=>r.position==='QB');run(`openAnalysisPlayerDetail('${qb.player_id}');`);assert.ok(!$('#player-detail-content').innerHTML.includes('TARGETS'));for(const label of ['COMPLETIONS','ATTEMPTS','PASS TD','INT','SACKS','RUSH ATT','PASS 2PT'])assert.ok($('#player-detail-content').innerHTML.includes('<th>'+label+'</th>'));run('closePlayerDetail()');
assert.ok(h.includes('.session-footer{position:static'));assert.ok(h.includes('#session-invites{width:100%}'));assert.equal(doc.querySelectorAll('.chart-top').length,3);assert.equal(doc.querySelectorAll('.table-top').length,2);
console.log('PASS: real manager-change handlers, all manager/view/sort combinations, place-gap fixtures, full-page history and nested return, complete side columns, quarterback position-specific production and shared navigation.');

console.log('PASS: current-week vs season, upcoming-week awaiting state, all 23 leagues, sort, ranked league drill-down and participant roster navigation, logout overlay clearing, position columns, player production/ownership, full-screen table, tie payouts/ranks, response filter and pair balances.');

let combinations=0;for(const year of ['2025','2026'])for(const manager of ['All',...data.managers.map(m=>m.key)])for(const side of ['All','Offense','Defense'])for(const pos of ['All','QB','RB','WR','TE','LB'])for(const query of ['','zzzz-no-player','brown']){run(`YEAR='${year}'`);for(const kind of ['stats','own']){$('#'+kind+'-manager').value=manager;$('#'+kind+'-side').value=side;$('#'+kind+'-team').value='All';$('#'+kind+'-position').value=pos;$('#'+kind+'-search').value=query;}run('renderAnalysis()');assert.ok(!$('#stats-table tbody').innerHTML.includes('NaN'));assert.ok(!$('#own-table tbody').innerHTML.includes('NaN'));combinations++;}console.log('PASS: '+combinations+' analysis combinations with the new controls and generated tables.');

let comparisons=0;for(const [year,season]of Object.entries(data.seasons)){run(`YEAR='${year}'`);const summary=run('computeSummary(YEAR)');assert.ok(Math.abs(Object.values(summary.current).reduce((a,b)=>a+b,0))<.00001);for(const league of season.leagues){ctx.inputWeeks=league.weeks;const isolated=run('isolatedWeeklyRows(inputWeeks)');for(const w of isolated)for(const r of w.rows){const roster=w.rosters?.find(x=>x.manager===r.manager);if(roster){assert.ok(Math.abs(r.pf-roster.pf)<.03);comparisons++;}}}}console.log('PASS: '+comparisons+' saved weekly points comparisons and season payout conservation.');
